runtime: python38
entrypoint: gunicorn -b :$PORT app:app --timeout 120

handlers:
  - url: /static
    static_dir: static
    secure: always
    expiration: "30d"

  - url: /.*
    script: auto
    secure: always